# DirectAU config for Amazon-CDs
# Usage:
# python run_recbole.py --config_files "amazon-cds_directau.yaml"

model: DirectAU
dataset: amazon-cds

# Data location and fixed benchmark split (.train/.valid/.test.inter)
data_path: ../data/
benchmark_filename: [train, valid, test]

# Training hyperparameters
learning_rate: 1e-3
weight_decay: 1e-6
gamma: 1
encoder: MF
train_batch_size: 512
